name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: KoreSamuel/potential@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: potential/.vuepress/dist/
        COMMIT_MESSAGE: Auto deploy from Github Actions
